---
- name: Install apache2 
  apt: name=apache2 state=present

- name: Install apache2 utils
  apt: name=apache2-utils state=present

- name: Enable apache rewrite
  apache2_module: name=rewrite state=present
  notify: restart apache 
